# This is a basic workflow to help you get started with Actions

name: ci_testing

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Set up requirements
        run: |
          $CONDA/bin/conda install pip
          pip install -e .
          $CONDA/bin/conda install -c conda-forge python-magic
          $CONDA/bin/conda install -c conda-forge ffmpeg
          $CONDA/bin/conda install -c pytorch torchvision
      - name: Run unit tests
        run: python -m unittest discover -s augly/tests/ -p "*"
