name: test_cupy
on:
  pull_request:
    branches: main
  push:
    branches: main
jobs:
  test_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: Jimver/cuda-toolkit@v0.2.4
        id: cuda-toolkit
        with:
          cuda: '11.2.2'

      - run:
          echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"

      - run:
          echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"

      - run: nvcc ---version